### ISSUE TITLE
allow alias to reference other alias

### ISSUE THREAD

**Issue by skostic96** [srele96/run-them-all#40]
Using config:

```yml
foo: echo foo
bar: echo bar
baz: echo baz
unified: foo bar baz
```

Running `run-them-all unified` should yield:

```txt
foo
bar
baz
```
