### ISSUE TITLE
allow inserting a variable inside string

### ISSUE THREAD

**Issue by skostic96** [srele96/run-them-all#41]
- We need a unique way to mark that we are referring to a variable without interfering with the command.
- We need a unique way to store variables so it doesn't interfere with users' aliases. We don't want to cut users short on one name. Is this feature worth it?

Using example config:

```yml
variables:
  path: C:\users\<username>\documents\my_project
foo: echo $path
bar: echo $path bar
variables: echo variables
```

Running `run-them-all foo` should yield:

```txt
C:\users\<username>\documents\my_project
```

Running the `run-them-all bar` should yield:

```txt
C:\users\<username>\documents\my_project bar
```
